### ISSUE TITLE
查詢車位等欄位

### ISSUE THREAD

**Issue by evanslify** [aaaddress1/buyHouseAnalyzer#2]
希望能夠新增一些搜尋條件：

1. 此筆交易有無車位
2. 車位類別

**Comment by aaaddress1** [comment]
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/8559056/155833091-b2869a51-5227-4f54-951b-0b385526c2ce.png">
done, check out commit: d08b20028d3f8fffb1c54b2a8d7ea69ccccd831f
